server:
  port: 8080

spring:
  #profiles:
    #active: dev
    #default: dev


  liquibase:
    enabled: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true

account:
  security:
    aes: "AES"
    secret: ${ACCOUNT_SECURITY_SECRET}

app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-ms: 7200000 # 2h

  contact:
    email: "mailto:sshibkodev@gmail.com"
    phone: "tel:+79149057065"
    telegram: "https://t.me/sergeshibko"
  version:
    number: "0.1.0"
    status: "TEST"

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springdoc: TRACE
    io.swagger: DEBUG
    com.fasterxml.jackson.databind: DEBUG

file:
  upload-dir: /app/uploads

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true